# -*- coding: utf-8 -*-
"""Human activity recognition using SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yljbck-NCcdO9phSa09qcmSqlMEde58Y
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/human-activity-recognition-with-smartphones")

print("Path to dataset files:", path)

import pandas as pd
train = pd.read_csv(path + "/train.csv")
test= pd.read_csv(path + "/test.csv")

train.head()

cat_col= [col for col in train.columns if train[col].dtype == 'object']
num_col= [col for col in train.columns if train[col].dtype != 'object']
num_col

cat_col

train['Activity'].value_counts()

X_train = train.drop(columns=['Activity'])
y_train = train['Activity']

X_test = test.drop(columns=['Activity'])
y_test = test['Activity']

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svm_linear= SVC(kernel='linear')
svm_linear.fit(X_train, y_train)
y_pred= svm_linear.predict(X_test)
accuracy_score(y_test, y_pred)

svm_rbf= SVC(kernel='rbf')
svm_rbf.fit(X_train, y_train)
y_pred= svm_rbf.predict(X_test)
accuracy_score(y_test, y_pred)

svm_poly= SVC(kernel='poly')
svm_poly.fit(X_train, y_train)
y_pred= svm_poly.predict(X_test)
accuracy_score(y_test, y_pred)